### ISSUE TITLE
pbj files produce an error

### ISSUE THREAD

**Issue by Harbs** [BowlerHatLLC/vscode-as3mxml#154]
Open the Graphics Royale package in VS Code. You will see 9 errors from included .pbj files used for PixelBender shaders.

I'm assuming that it's not reasonable for VS Code to properly read those files and they should probably be excluded from the language engine processing.

**Comment by joshtynjala** [comment]
Thanks, I'll look into it. Hopefully there is a way to exclude them...

**Comment by joshtynjala** [comment]
I have investigated, and this looks like a bug in royale-compiler.

As I understand it, to embed a pbj file, the compiler needs to generate a class that extends flash.display.Shader. This seems to happen in PBJTranscoder.java. In the analyze() method in EmbedCompilationUnit.java, it asks the transcoder what base class is needed, and then it tries to find the IDefinition for that class. The definition for Shader doesn't exist in JS projects, though. Basically, the compiler assumes that all transcoder base classes exist because, when the compiler used to be SWF-only, they always did.

It could be a simple fix to modify this analyze() method to check if the IDefinition[] array returned by findAllDefinitionsByName() is empty, and then create some kind of compiler error if it is. analyze() receives a parameter of type Collection<ICompilerProblem>, so I think someone can just add additional problems to this collection and the compiler will know what to do with them.

As far as I can tell, there's nothing I can do in vscode-nextgenas to avoid this error (other than to remove it from the list of errors manually). The proper solution is to fix it in the compiler.

**Comment by joshtynjala** [comment]
apache/royale-compiler@d86a6dadfae13f0e456ec69c47da2aa28324ca01
