### ISSUE TITLE
How to create mobile version in ubuntu

### ISSUE THREAD

**Issue by aldyahsn** [BowlerHatLLC/vscode-as3mxml#315]
Hi. I am using ubuntu. Finally can develop as3 on ubuntu. Anyway, I am used to develop adobe air in flashdevelop(windows) to target mobile version. Can I do that in Ubuntu? I just checked that Adobe Air SDK only provide windows and mac version. 

Any suggestion what best SDK to create mobile version in ubuntu? I only use Adobe Air SDK so far.

**Comment by joshtynjala** [comment]
Unfortunately, I don't think that mobile AIR development will be possible on Linux. Adobe has not updated AIR on Linux since version 2.6. Technically, this version supported both iOS and Android, but it probably won't be able to produce apps that can run properly on modern devices. Additionally, AIR 2.6 is equivalent to Flash Player 10.2, so you won't have access to modern APIs released since 2011.

To develop for AIR or Flash Player on Linux, you should use the Apache Flex SDK. You can find instructions for setting up this SDK on Linux here:

https://cwiki.apache.org/confluence/display/FLEX/Installation+help#Installationhelp-Ant-basedinstaller

The Flex SDK Installer app doesn't run on Linux, but you can use Ant to run an installation script that is included with the SDK.

A while back, I tested the SWF debugger in VSCode on Linux, and I was able to connect the debugger to Flash Player. While Adobe stopped updating AIR, Flash Player is still updated with the latest version on Linux. You can download the debug Flash Player for Linux here:

https://www.adobe.com/support/flashplayer/debug_downloads.html

They have both the browser plugin and the standalone "projector" version of Flash Player. For anyone wanting to try it, I would recommend using the projector version since browsers are going to drop support for Flash Player sometime later this year in 2019.

Obviously, if you work with Flash Player, you won't have access to AIR APIs, so if you're doing AIR development only, this probably won't be a great workflow for you.
