### ISSUE TITLE
AIR XML Descriptor file for each target (iOS/Android/Desktop)

### ISSUE THREAD

**Issue by 22Round** [BowlerHatLLC/vscode-as3mxml#320]
how can I set xml descriptor, icons and launch images for each target iOS/Android/Desktop?

**Comment by joshtynjala** [comment]
Since the AIR application descriptor is designed to include configuration for all platforms in the same file, *asconfig.json* does not allow you to specify a separate AIR application descriptor for each platform. 

However, you can customize how an AIR app is packaged for different platforms in a single *asconfig.json* file. For instance, you can create an `ios` sub-section inside the `airOptions` section to customize the files that you include, since iOS usually has extra launch images and things. See [asconfig.json: Adobe AIR options for multiple platforms](https://github.com/BowlerHatLLC/vscode-as3mxml/wiki/asconfig.json#adobe-air-options-for-multiple-platforms) for details. (You've probably already done this to provide signing options for different platforms... but it supports overriding more than just signing options).

That said, you can also create multiple *asconfig.json* files for a single project, if you prefer. You'll still need to have the main *asconfig.json* file to enable code intelligence, but you can create more *asconfig.\*.json* files with different configuration options for different targets. VSCode detects any file named like *asconfig.\*.json* file, and it will provide separate tasks for each one.

With this in mind, you could create *asconfig.ios.json* and *asconfig.android.json*, and that would allow you to provide different AIR application descriptors for these two platforms.

**Comment by 22Round** [comment]
@joshtynjala  thanks for detail explanation, asking because, I am using different ANE's for iOS and Android.
maybe naming  _asconfig.ios.json_ and _asconfig.android.json_ would be solution, will try what you advised.
