### ISSUE TITLE
[Bug] AIR Window Closes. No Errors.

### ISSUE THREAD

**Issue by angelhdz** [BowlerHatLLC/vscode-as3mxml#334]
AIR Window Closes by itself in 2 projects. No errors are shown.  All the config files seems to be ok, and they should because I create those files with a Python Program I made for creating projects, and it worked perfectly until this day.

![2019-03-01_11-18-11](https://user-images.githubusercontent.com/10191085/53649163-fa22a680-3c17-11e9-83fc-10bd707566f9.gif)

Tried restarting the AS Server. 
Tried restarting VSCode. 

Then it came to me to switch the AIR SDK, from v31.0 to v.28.0, and **it's working!**

**Then I noticed another issue:** 

When I hit the "Select And Start Debugging Configuration" button at the bottom-left side of VSCode,  it chooses the right project to build/debug.

When I hit CNTRL + ENTER (Quick Compile & Debug), it chooses the wrong project! Even after selecting the desired project from the drop-down menu!

**Comment by angelhdz** [comment]
### Update (First Issue)

Switched to FlashDevelop. No issues with either AIR SDK 31.0 or 28.0. All AIR Windows stay open.

**Comment by angelhdz** [comment]
### Solved (first issue)

With all the struggle to get an AIR Mobile profile to work, I made a new application.xml descriptor file, and the AIR version was differente than the SDK's version. This time was a mistake of mine.

### The other issue is still happening. Quick Compile & Debug is still selecting the wrong project.

**Comment by joshtynjala** [comment]
Yes, when AIR simulator crashes, it usually means that the version in the descriptor XML file is wrong.

Quick Compile & Debug builds asconfig.json only. If you have any other asconfig files in your workspace, they cannot be used with Quick Compile & Debug. For debugging, it uses the configuration that is currently selected in the drop-down. It does not attempt to change the selected configuration in any way.

**Comment by angelhdz** [comment]
Alright. 

### Question

If **Quick Compile & Debug** won't select a project, why it displays a drop down to select a project in the first place? That's what's bugging me cause is more steps to achieve something that is supposed to be "Quick". 

Is there a way I can disable that drop down or it has to be made in the extension's source code?

My solution is sticking to **CTRL + SHIFT + B** (Run Build Task) and then **F5** (Start Debugging).

**Comment by joshtynjala** [comment]
> If Quick Compile & Debug won't select a project, why it displays a drop down to select a project in the first place? 

If you have multiple application projects in the same workspace, you need to choose which one to **compile**. It can't guess that for you.

> Is there a way I can disable that drop down or it has to be made in the extension's source code?

To disable the drop-down, your workspace should contain only one application project (but you may also have any number of library projects, if you wish). If there is only one app, it automatically knows to compile that one.

> My solution is sticking to CTRL + SHIFT + B (Run Build Task) and then F5 (Start Debugging).

This seems like a perfectly reasonable choice in a workspace with multiple apps. However, you can improve this workflow a bit:

If you add a preLaunchTask to your debug configuration, you can skip Ctrl+Shift+B and you only need F5. Using preLaunchTask allows VSCode to automatically build before debugging. This works in any language supported by VSCode.

The main advantage of Quick Compile & Debug is that it keeps the AS3 compiler in memory, so that re-compiles are a little bit faster. However, you're not required to use it. In fact, it's still labeled **Experimental** so that it's clear that it may not work well for everyone.

**Comment by angelhdz** [comment]
Perfect.
