### ISSUE TITLE
asconfig.json: default "default-size" not read from application.xml

### ISSUE THREAD

**Issue by Adolio** [BowlerHatLLC/vscode-as3mxml#348]
Hello Josh,

I just faced an issue with a bad `Starling`'s `viewport` and I then figured out that I needed to specify the `default-size` compile option in my `asconfig.json` (same values as in `application.xml` -> `initialWindow` -> `width/height`).

Did I missed something or could we imagine picking the default size right from the `application.xml` if not explicitely defined in the `asconfig.json`?

Best,
Aurélien

**Comment by joshtynjala** [comment]
It's been my experience that the native stage may not necessarily be the correct size immediately when the app starts up, and that it's important to listen for resize events. I always make sure that my Starling apps can handle resizing gracefully.

If you prefer, you can use `[SWF]` metadata on your startup class, instead of using compiler options like default-size and default-background-color:

``` as3
[SWF(width="960",height="640",frameRate="60",backgroundColor="#4a4137")]
public class My app extends Sprite
```

**Comment by Adolio** [comment]
Alright. I don't mind adding the resolution either in the compile options or in the `[SWF]` metadata. What I don't like is having twice the same constant in two places... but you're right they don't have exactly the same purpose.

Anyway I can live with it ;) It was just a bit painful to find the source of the issue even with a very simple project. I hope this thread will help anyone running in the same issue.

Thanks Josh!
