### ISSUE TITLE
How to create AIR app using HTML

### ISSUE THREAD

**Issue by velara3** [BowlerHatLLC/vscode-as3mxml#367]
Is it possible to create an AIR app using HTML? 

I've found this related post: 

https://github.com/BowlerHatLLC/vscode-as3mxml/wiki/Create-a-new-ActionScript-project-in-Visual-Studio-Code-that-targets-Adobe-AIR-for-desktop-platforms

**Comment by joshtynjala** [comment]
In theory, you would just point the content in your AIR application descriptor to an HTML file instead of a SWF file. That's my best guess because I've never actually used AIR with pure HTML. These days, Electron would be the better choice, obviously.

Be aware that Adobe hasn't updated the version of WebKit used by AIR in many years, so you'll be stuck with older browser APIs.

**Comment by velara3** [comment]
OK So I have an HTML app running AS3 or Royale running in Electron now.

**Comment by joshtynjala** [comment]
Thanks for sharing! I'm sure that the Royale community would love to see a guide for using Electron. If you write it, be sure to share on their mailing list too.
