### ISSUE TITLE
Unused type selector keep all selectors

### ISSUE THREAD

**Issue by velara3** [BowlerHatLLC/vscode-as3mxml#369]
I'm getting messages that a few options are not supported:

>Invalid asconfig.json:
$.compilerOptions.keep-all-type-selectors: is not defined in the schema and the schema does not allow additional properties
$.type: is missing but it is required

My asconfig.json:

      "keep-all-type-selectors":true,
      "show-unused-type-selector-warnings": false,

Is there anyway I can add support for these?

**Comment by joshtynjala** [comment]
When a compiler option is missing in `compilerOptions`, you can still use it by putting it in `additionalOptions` instead. Then, just let me know in an issue, and I'll try to get it added officially.

I'll try to post some more info tomorrow about what all needs to be modified to add a new option, if you'd like to do a pull request.

**Comment by joshtynjala** [comment]
Had a few minutes to put together the links.

To add a new compiler option, you first need to add it to the *asconfig.json* schema:

https://github.com/BowlerHatLLC/vscode-as3mxml/blob/master/distribution/src/assembly/schemas/asconfig.schema.json

Then, a constant with the name needs to be added here:

https://github.com/BowlerHatLLC/vscode-as3mxml/blob/master/asconfigc/src/main/java/com/as3mxml/asconfigc/compiler/CompilerOptions.java

The parser needs to be updated to look for the option:

https://github.com/BowlerHatLLC/vscode-as3mxml/blob/master/asconfigc/src/main/java/com/as3mxml/asconfigc/compiler/CompilerOptionsParser.java

Finally, one or more tests need to be added to be sure it's being parsed correctly:

https://github.com/BowlerHatLLC/vscode-as3mxml/blob/master/asconfigc/src/test/java/com/as3mxml/asconfigc/compiler/CompilerOptionsParserTests.java

That's for the VSCode extension. The command line *asconfigc* tool needs to be updated to because they should both be able to handle the same set of options.

Here are a similar set of files for that:

https://github.com/BowlerHatLLC/asconfigc/blob/master/schemas/asconfig.schema.json
https://github.com/BowlerHatLLC/asconfigc/blob/master/src/com/as3mxml/asconfigc/CompilerOptions.as
https://github.com/BowlerHatLLC/asconfigc/blob/master/src/com/as3mxml/asconfigc/CompilerOptionsParser.as
https://github.com/BowlerHatLLC/asconfigc/blob/master/test/src/tests/CompilerOptionsTests.as

**Comment by velara3** [comment]
I'm not setup to update the compiler but I could easily clone the repo, add new options, do a pull request for a 99% there goal :)

**Comment by joshtynjala** [comment]
Which compiler needs to be updated?

**Comment by velara3** [comment]
That's for the extension? I see. I'll have to do some reading... :)

**Comment by joshtynjala** [comment]
Yeah, the Apache Royale compiler that's used for code intelligence should be able to accept any compiler option that originally existed in the classic Flex SDK compiler and ASC 2.0.

It's just that I haven't added all possible options to the `compilerOptions` section of *asconfig.json* yet. I created that file format for the VSCode extension.
