### ISSUE TITLE
Use AS3 for the main.js main process in Electron in a Royale or AS3 only project

### ISSUE THREAD

**Issue by velara3** [BowlerHatLLC/vscode-as3mxml#377]
I've put together a guide to create a desktop app with Royale and Electron and this extension [here](https://royale.codeoscopic.com/how-to-create-a-desktop-application-with-royale-and-electron/).

This lets the developer write their app in MXML and AS3 on the "client" side (the renderer process) and on the "server" side (the Main process - the code in main.js) they use JS (ES6). 

Is there a way to use AS3 in the main process? Can I transpile an AS3 class to main.js? I've found a great article [here](https://royale.codeoscopic.com/how-to-create-a-desktop-application-with-royale-and-electron/) about transpiling AS3 to node.js. :)

**Comment by velara3** [comment]
It looks like there are developers using TypeScript for their Electron projects, http://www.jamesirl.com/posts/typescript-electron.

**Comment by joshtynjala** [comment]
As you probably know, the Royale compiler can generate code for Node.js. Here's the relevant project type in VSCode:

https://github.com/BowlerHatLLC/vscode-as3mxml/wiki/Create-a-new-ActionScript-project-in-Visual-Studio-Code-that-targets-Node.js

The *index.js* file that is generated by the Royale compiler in *bin/js-debug* or *bin/js-release* may work as your main process in Electron. However, I have not tested this.

You may need to tell the Royale compiler to create a Node.js library instead. Normally, when you use the "node" config, the target is "JSNode", which produces a standalone script that you can run from the command line. However, You can tell it to use "JSNodeModule" and it will produce a CommonJS module that can be used with `require()` in non-AS3 projects. The *asconfig.json* file in VSCode would need a different `targets` compiler option, like this:

```json5
{
	"config": "node",
	"compilerOptions": {
		"targets": [
			"JSNodeModule"
		]
	},
	"files":
	[
		"src/Main.as"
	]
}
```

Again, I don't know if that's necessary or it, but it may be something that you need to try.

The "JSNodeModule" target isn't really documented anywhere, by the way. I added it because I needed it for a project, but I just never had time to write anything down about it.

**Comment by velara3** [comment]
I'll give it shot. I've created some getting started AS3 projects for Electron (to start) here, https://github.com/velara3/as3. 

For Electron projects there is a Renderer process and a Main process. I've got AS3 and Royale working with the Renderer process and JavaScript and TypeScript working for the Main process (4 projects). I haven't been able to get AS3 for the Main process but I think I'm getting close (5th and 6th project). 

I'm working on having the AS3 process working for the main process possibly by adding a second asconfig.

**Comment by joshtynjala** [comment]
> I'm working on having the AS3 process working for the main process possibly by adding a second asconfig.

Yes, separate *asconfig.json* files will definitely be required for the main and renderer processes. The output JS is fundamentally different, since one targets Node.js-style modules and the other HTML.

**Comment by velara3** [comment]
I've mostly got this working here, https://github.com/velara3/as3/tree/master/as3-as3-electron.

**Comment by joshtynjala** [comment]
@velara3 Cool, thanks for sharing!
