### ISSUE TITLE
Code intelligence will not be available for this file.

### ISSUE THREAD

**Issue by jnpatrick99** [BowlerHatLLC/vscode-as3mxml#380]
This issue is similar to https://github.com/BowlerHatLLC/vscode-as3mxml/issues/265 except I'm using older Adobe Flex AS3  libraries. 

1) If I include Flex SDK sources into "source-path" I get like 100 compiler errors for Flex SDK .as files because (my guess) Apache royale cannot handle older libraries
2) If I don't include Flex SDK sources I get "Code intelligence will not be available for this file" errors for every .as file from Flex SDK

Is there a way to suppress this message for older Flex SDKs? Thank you.

**Comment by joshtynjala** [comment]
> I get like 100 compiler errors for Flex SDK .as files because (my guess) Apache royale cannot handle older libraries

It should be able to handle any ActionScript code. What kind of errors are you seeing? Most SDKs have source files separated across multiple projects (one for each SWC file), so could it be that you have not added everything?

> I get "Code intelligence will not be available for this file" errors for every .as file from Flex SDK

Yeah, this is behaving as-designed. It happens when you open a source  file from inside any SDK, including Royale. Only your project's source files will have code intelligence. You can open a file from the SDK to read the code, but code intelligence features are purposefully disabled.

I'd like to improve this, but I haven't figured out how to do it right. As I mentioned, source files from an SDK are not located in a single convenient location, so there's a good chance of missing some dependencies that will result in false-positive errors that are not relevant to your project. That would be very confusing, so disabling code intelligence for files in the SDK is preferable.

**Comment by jnpatrick99** [comment]
Thank you for the clarification!

> It should be able to handle any ActionScript code. What kind of errors are you seeing? Most SDKs have source files separated across multiple projects (one for each SWC file), so could it be that you have not added everything?
> 

For one of the projects I'm using Flex SDK 3.6, here are the errors I'm receiving:
```BoxLayout.as: Call to isVertical is not a function```
(The isVertical is a private function defined in the same file)
```CrossDomainRSLItem.as: Call to hasFailover is not a function.```
(Same, defined in the same file)
```ListRowInfo.as: Call to a possibly undefined method pop through a reference with static type ListRowInfo.```
and etc etc etc

Those are original Adobe sources and the errors look weird like compiler doesn't understand the source.

> Yeah, this is behaving as-designed. It happens when you open a source file from inside any SDK, including Royale. Only your project's source files will have code intelligence. You can open a file from the SDK to read the code, but code intelligence features are purposefully disabled.

Yes I understand that, the problem is I get these errors in the Problems of VS Code so every time the code is edited a check needed if those are actual code errors or just warning messages about code intelligence.

**Comment by joshtynjala** [comment]
> in the Problems of VS Code so every time the code is edited a check needed if those are actual code errors or just warning messages about code intelligence.

Hmm... I can't say that has ever bothered me. Maybe I tend to look in the status bar where each category of "Problem" has its own separate count rather than looking at the total sum. In the status bar, VSCode usually displays 2 or 3 icons, for ❌ errors, ⚠️ warnings, and ℹ️ info.

**Comment by joshtynjala** [comment]
It turns out that some of my recent refactoring made it much easier to add code intelligence to SDK files. You won't need to worry about this message anymore, starting in v0.21.

**Comment by jnpatrick99** [comment]
Thank you!
