### ISSUE TITLE
SWF debug complier take a long long time and no response

### ISSUE THREAD

**Issue by Hakunametata** [BowlerHatLLC/vscode-as3mxml#389]
my air and swf player version is 32.0

![image](https://user-images.githubusercontent.com/19553669/60670290-e4154300-9ea2-11e9-9ec9-aae723e87564.png)

i config my project as wiki ,then start complier and debug 

complier:
![image](https://user-images.githubusercontent.com/19553669/60670390-12931e00-9ea3-11e9-8a3a-a2516d9c7314.png)

debug run:
![image](https://user-images.githubusercontent.com/19553669/60670436-30f91980-9ea3-11e9-9231-094b04b2a79b.png)

**Comment by Hakunametata** [comment]
i figure it out  the correct version is 21.0 ,but why......

**Comment by joshtynjala** [comment]
From your screenshot, you seem to be compiling with an SDK named 4.6.0+28.0.0. I assume the 28.0.0 refers to the AIR SDK version, so that one wouldn't support the AIR 32 namespace. It should be able to support something newer than AIR 21, though.

I think that you're using the npm version of asconfigc and not the built-in one. It's possible that you are compiling with one SDK and debugging with a different one.

What SDK is set in VSCode's workspace settings? To find it, you can either click on the status bar item or find the `as3mxml.sdk.framework` in your .vscode/settings.json file.

**Comment by Hakunametata** [comment]
> From your screenshot, you seem to be compiling with an SDK named 4.6.0+28.0.0. I assume the 28.0.0 refers to the AIR SDK version, so that one wouldn't support the AIR 32 namespace. It should be able to support something newer than AIR 21, though.
> 
> I think that you're using the npm version of asconfigc and not the built-in one. It's possible that you are compiling with one SDK and debugging with a different one.
> 
> What SDK is set in VSCode's workspace settings? To find it, you can either click on the status bar item or find `as3mxml.sdk.framework` in your .vscode/settings.json file.

yeah you are right,i change the air version to 21.0 and it works.
