### ISSUE TITLE
Fade out unused ActionScript imports

### ISSUE THREAD

**Issue by gonetoofar** [BowlerHatLLC/vscode-as3mxml#404]
Vscode indicates unused code in javascript and typescript. Can this be done in actionscript?
Flashbuilder detects unused import statements.

**Comment by joshtynjala** [comment]
Showing unused imports is something that I plan to work on. Unfortunately, the compiler that is used to power code intelligence doesn't provide any kind of warnings/hints about unused imports, so I need to find them manually.

That said, I already have some working code that can find unused imports because I needed to find them for the Organize Imports command. I've been thinking that it should be possible to reuse this existing code after I ask the compiler for errors/warnings. I can append my own custom hints that will tell VSCode to fade out those lines.

**Comment by joshtynjala** [comment]
Closed in commit 0a2d290e9a16b6b7b484c4debf663d857cac244b
