### ISSUE TITLE
Maven multi module project support

### ISSUE THREAD

**Issue by lonelyma1021** [BowlerHatLLC/vscode-as3mxml#435]
I have a air desktop project managed by maven(via flexmojos-maven-plugin). The top level project has no source code, it’s just a parent pom project. The modules of it are applicarion or library projects. Now my questions are:

- How to configure the project? The wiki provides sample `asconfig.json` for different kinds of project. But I still don’t know how to configure my project’s top level `asconfig.json` file, since it neither a application nor a library project. Due to that the as3mxml language server seems not working.

- The as3mxml extension does not support maven. It can not resolve dependencies from `pom.xml`. That means I have to create a lib folder and copy all swc files into it. It’s meaningless for me because it’s maven’s job.

Will, do u have any plan about adding maven support for flex?

**Comment by joshtynjala** [comment]
> But I still don’t know how to configure my project’s top level asconfig.json file, since it neither a application nor a library project.

The root folder of your workspace must be an application or library project. Applications/libraries cannot be in subfolders or code intelligence will not be enabled for them.

VSCode supports something called [multi-root workspaces](https://code.visualstudio.com/docs/editor/multi-root-workspaces). If you want all of your applications/libraries in the same workspace, then you need to add each individual module that represents an application or library as a root. Then, you can create a separate asconfig.json file inside each root to configure it.

> Will, do u have any plan about adding maven support for flex?

I do not. I suspect that it would be a huge undertaking with little benefit.

I might consider Maven support for Apache Royale in the future (unlikely, but possible). However, Maven usage with Flex was never common even when Flex was at its highest level of popularity. These days, I'd probably be supporting you and no one else.

> That means I have to create a lib folder and copy all swc files into it. It’s meaningless for me because it’s maven’s job.

You could probably use the paths to the SWC files in your Maven repository instead of copying them into your project folder.
