### ISSUE TITLE
unable to open flex-config.xml

### ISSUE THREAD

**Issue by Shaunmax** [BowlerHatLLC/vscode-as3mxml#451]
When trying to debug an Animate Project I am getting a problem which says : - 
unable to open'/Applications/Adobe Animate/AIR32.0/frameworks/flex-config.xml

I am on Mac and would like to know how to fix it!

**Comment by joshtynjala** [comment]
There are two versions of the AIR SDK. One has its own compiler, and one does not. The version without a compiler is meant to be merged with another SDK, like the Flex SDK or the Feathers SDK. It's possible that Adobe Animate can also use this version of the AIR SDK, since it has its own internal compiler.

The `as3mxml.sdk.framework` setting in VSCode must be set to an SDK that contains a compiler.

**Comment by Shaunmax** [comment]
How do we merge it with Flex sdk?

**Comment by joshtynjala** [comment]
https://helpx.adobe.com/x-productkb/multi/how-overlay-air-sdk-flex-sdk.html

Alternatively, you could use the Apache Flex SDK installer.

Another option (which is probably easiest!) is to download the version of the AIR SDK that already contains a compiler. Here's Adobe's [AIR download page](https://www.adobe.com/devnet/air/air-sdk-download.html).

**Comment by Shaunmax** [comment]
Yes, I downloaded the AIR SDK with compiler option and it worked! Everything works fine! but I dont see any trace statements in the output panel and in the problems panel I have a msg - "Overlapping source path enteries" with a path to src folder in my project folder. but i dont have a folder src in it. when i try to add a empty folder it say unable to open src ?????

**Comment by joshtynjala** [comment]
I'll need to see your asconfig.json file before I can make any suggestions about your issues.

**Comment by Shaunmax** [comment]
its the same from the wiki:-

```
{
	"animateOptions": {
		"file": "MyApp.fla"
	},
	"compilerOptions": {
		"source-path": [
			"src"
		]
	},
	"mainClass": "Main"
}
```

**Comment by joshtynjala** [comment]
With the contents of your _asconfig.json_file, VSCode expects your project to have a file named _src/Main.as_. In Animate terminology, that is your "document class". If your Animate project doesn't have a document class, you need to create one to use VSCode.

I don't think that I was able to successfully find a way to display `trace()` statements in VSCode from Animate. As I recall, the file where Animate saves trace() output could not be opened while Animate was running Test Movie or Debug Movie.

**Comment by Shaunmax** [comment]
but in animate document class needs to be saved in the root folder i.e same
location as .fla file. is there a way to set it same as root folder instead
of src?

**Comment by joshtynjala** [comment]
The document class isn't required to be in the root folder. You can change the _source path_ in your _.fla_ file. In your ActionScript 3.0 settings, there are three tabs: Source path, Library path, and Config constants. In the Source path tab, you probably have an entry for `.`, which tells that to use the same folder as the _.fla_ file. You can change that to `src` instead.

Alternatively, you can set `source-path` in _asconfig.json_ to `.` instead of `src`.

**Comment by Shaunmax** [comment]
Thanks Josh will try that!
