### ISSUE TITLE
Reference environment variables in asconfig.json

### ISSUE THREAD

**Issue by Zageron** [BowlerHatLLC/vscode-as3mxml#465]
At this point I have been unable to. Is there a known solution for this?
```
{
    "name": "R3::HASH_STRING",
    "value": "%R3_HASH_STRING%"
}
```

I've scoured the code, and do see that you have some specific tokens that you use System.getProperty(...) for.

Would you be willing to add a path for arbitrary variable grab attempts to add to the --define list?

We are looking to inject secrets at build time so they aren't stored in the repository. If you have a way of doing this, other than storing a private version of the asconfig.json file, it would be much appreciated.

**Comment by joshtynjala** [comment]
When considering features like this, I generally try to check what TypeScript supports in its tsconfig.json file, which was the inspiration for asconfig.json. As best I can tell, you cannot reference environment variables in tsconfig.json, so I am wary to support this myself.

A separate asconfig.secrets.json file (with `"extends": "asconfig.json"` so that you don't need to duplicate content) is what I recommend.

**Comment by Zageron** [comment]
I'll give this a try and see how I fair. Thanks for the suggestion.

**Comment by Zageron** [comment]
Extends didn't do it for me, but I ended up using a template engine to scan the file and replace my token.
