### ISSUE TITLE
[Feature Request] Add a valid list of Royale CSS valid properties

### ISSUE THREAD

**Issue by carlosrovira** [BowlerHatLLC/vscode-as3mxml#488]
Hi Josh,

In VSCode if I add to my settings.json a config like the following:

`"css.lint.validProperties": ["IItemRenderer", "ISelectableItemRenderer"]`

VScode consider `IItemRenderer` and `ISelectableItemRenderer` valid css properties removing warnings.

Could AS3&MXML extension add a list of Royale CSS valid properties on its own to avoid users configure this each time they install VSCode?

I think would be a nice addition

Thanks

**Comment by joshtynjala** [comment]
Since it is a setting for CSS and not for AS3 or MXML, it could potentially cause issues with non-Royale projects that use CSS. With that in mind, I don't think that this belongs in the AS3 & MXML extension. Perhaps you could create a separate extension for Royale that adds this sort of things so that people can opt-in if they really want it.
