### ISSUE TITLE
From Flex 4.6 SDK to AIR 32

### ISSUE THREAD

**Issue by zabdoul60460** [BowlerHatLLC/vscode-as3mxml#490]
Hi,
When I try to build my AIR project (Terminal/run build task / Actionscript compile debug).
An error appear in main application file (Main.mxml).

Indeed 's:WindowedApplication' seems to be deprecated
Could you help me to solve that.

And what is the best process to convert a projet form Flex 4.6 SDK to AIR 32 ?

Best regards

**Comment by joshtynjala** [comment]
If you want to use components like <s:WindowedApplication>, you need to continue to use the Flex SDK. The AIR SDK doesn't include any of Flex's Spark or MX UI components. They're not deprecated. It's just a different SDK.

**Comment by zabdoul60460** [comment]
Thanks I to do that but now some errors appears with embedded files

`      [Embed( source = "icon/commun/glossaire.png" )]`
col: 9: Error: Impossible
to solve icon/common/glossary.png for transcoding

Do you know why ?

Thanks for helping

**Comment by joshtynjala** [comment]
The AS3 & MXML extension resolves paths to embedded files slightly differently to the Flex SDK. The AS3 & MXML follows the rules of the ASC 2.0 compiler, which is more strict (ASC 2.0 is a different AS3 compiler included with the AIR SDK).

If you compile your project, you probably won't get the same error. VSCode will compile using the Flex SDK that you configured, so it will use the less strict rules. So, if you don't mind seeing the errors in the editor, you can safely ignore them.

If you want the errors to go away entirely, you'll need to change the [Embed] path so that the Flex SDK and the AS3 & MXML extension are both happy. I can assure that that there is always a way to do this.

Just adding a `/` to the beginning of the path sometimes works.

```
[Embed( source = "/icon/commun/glossaire.png" )]
```

This option tells the compiler to look for the embedded asset starting from the root of the source-path. So, if your .as file is *src/com/example/MyClass.as*, then it will try to find *src/icon/commun/glossaire.png*. Without the `/` at the beginning, it was lookg for a file at *src/com/example/icon/commun/glossaire.png* instead.

Or you might need something like this instead:

```
[Embed( source = "/../icon/commun/glossaire.png" )]
```

This resolves to *src/../icon/commun/glossaire.png*.

I hope that helps!
