### ISSUE TITLE
Debugger broken in VSCode 1.47.0

### ISSUE THREAD

**Issue by carlosrovira** [BowlerHatLLC/vscode-as3mxml#491]
Hi Josh,

I think something changed in latest VSCode version since 1.47.0, since I can't launch Royale debug or release in Chrome and Firefox. I think the changes affect to AS3&MXML internals.

**Comment by joshtynjala** [comment]
The latest VSCode update includes a new JavaScript debugger:

https://code.visualstudio.com/updates/v1_47#_new-javascript-debugger

It's possible that your launch.json file needs some tweaks after this change. However, I don't have anything to suggest at this time because I don't have enough information about what "broken" means. At the minimum, you should include the text of the error message you are seeing, or a detailed description of the unexpected behavior, if there's no error message.

For the record, the AS3 & MXML extension doesn't know how to debug Royale apps. That has always been handled by the Chrome debugging extension (and the Firefox debugging extension) used for any JS app.

**Comment by carlosrovira** [comment]
Hi Josh,

I have installed Chrome ad Firefox debuggers. When I launch the chrome task for Tour De Jewel:

```
{
            "name": "Launch Chrome (Debug version)",
            "type": "chrome",
            "request": "launch",
            "file": "${workspaceRoot}/target/javascript/bin/js-debug/index.html",
            "sourceMaps": true
        }
```
Chrome opens but don't open the TSJ app it remains on google page and after some seconds I get:

```
Error processing launch: Error: Could not attach to main target
	at /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/ms-vscode.js-debug/src/extension.js:1:33166
	at async f.prepareLaunch (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/ms-vscode.js-debug/src/extension.js:15:2619729)
	at async f.launch (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/ms-vscode.js-debug/src/extension.js:15:2620329)
	at async t.Binder.captureLaunch (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/ms-vscode.js-debug/src/extension.js:73:25637)
	at async t.Binder._launch (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/ms-vscode.js-debug/src/extension.js:73:25208)
	at async Promise.all (index 6)
	at async t.Binder._boot (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/ms-vscode.js-debug/src/extension.js:73:24468)
	at async t.default._onMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/ms-vscode.js-debug/src/extension.js:15:2459238)
```

I tryied nightly build too, and error is less verbose, just this:

I'm getting "Could not attach to main target"

**Comment by joshtynjala** [comment]
You might try removing the Chrome debugger extension. VSCode's new "JavaScript" debugger extension is supposed to take precedence now.

**Comment by carlosrovira** [comment]
I removed both debuggers, and change type to "pwa-chrome", but results are the same

**Comment by joshtynjala** [comment]
Maybe there was some change to launching a local file without a server. You could running your app with a local development server instead. For HTML/JS apps for any framework, it's almost always better to do that anyway, since the browser behaves somewhat differently with files that don't come from servers.

Beyond that, you may need to look for a solution elsewhere. I don't know why it might be failing, but it's not the AS3 & MXML extension that's causing the issue.

**Comment by carlosrovira** [comment]
Many thanks Josh, I'll try some local server and see if I can get it to work.
Anyway if find something more will reflect here so others can find a solution although is not specific to this extension.
Thanks

**Comment by joshtynjala** [comment]
@carlosrovira I think that this will work (without a server):

```
{
    "name": "Launch Chrome (Debug version)",
    "type": "chrome",
    "request": "launch",
    "url": "file:///${workspaceRoot}/target/javascript/bin/js-debug/index.html",
    "webRoot": "${workspaceRoot}/target/javascript/bin/js-debug",
    "sourceMaps": true
}
```

**Comment by joshtynjala** [comment]
I also confirm that changing the `debug.javascript.usePreview` setting to `false` works for me.

**Comment by carlosrovira** [comment]
Hi @joshtynjala, many thanks! I could launch again following your instructions! :)
