### ISSUE TITLE
I have no build tasks 

### ISSUE THREAD

**Issue by oscargoldman** [BowlerHatLLC/vscode-as3mxml#548]
The documentation suggests there should be some preconfigured tasks added by the extension but I don't have any. I'm able to quick compile and debug from the command palette but there are no tasks for building. I've tried deleting the extension and reinstalling. Any ideas?

**Comment by oscargoldman** [comment]
here it is... had to change extension as json is not supported.
[asConfig.md](https://github.com/BowlerHatLLC/vscode-as3mxml/files/7073028/asConfig.md)

**Comment by joshtynjala** [comment]
Unfortunately, I couldn't reproduce the issue by using your file on my computer. This very strange. All projects should at least have "ActionScript: compile debug - asconfig.json" and  "ActionScript: compile release - asconfig.json" listed as available tasks at minimum. The only reason I can find why these two tasks would not show up is if asconfig.json were missing, or if your SDK were invalid. However, since you say that code intelligence like completion is working for you, both of these should be fine.

Can you send me a screenshot of what the file explorer in VSCode looks like? You can collapse most of the directories, but I'd say keep .vscode visible. If you can open src while not requiring scrolling, that's fine too. I just want to see if there's something unexpected about your project's file system structure that I might be missing. Thanks!

**Comment by oscargoldman** [comment]
I'm wondering if this is related to the fact that my install of VS Code is
not on my C drive? Could that be it? My .vscode has a launch.json file and
a settings.json file.

**Comment by joshtynjala** [comment]
No, I don't think it matters if you installed VSCode on another drive.
