### ISSUE TITLE
Error: This tag could not be resolved to an ActionScript class. It will be ignored.

### ISSUE THREAD

**Issue by ULSashido** [BowlerHatLLC/vscode-as3mxml#571]
This is a third attempt over 2 years I've been trying to get AIR SDK running on my new Mac (still using old Mac with Flash Builder dedicated to Air Apps).

So I have done exactly as the [documentation](https://github.com/BowlerHatLLC/vscode-as3mxml/wiki/Debug-an-Adobe-AIR-desktop-application-with-Visual-Studio-Code) described:
<img width="434" alt="Screen Shot 2021-12-07 at 8 07 50 AM" src="https://user-images.githubusercontent.com/80773129/145034804-c8678745-bede-40cb-b821-8b2deaf6b5c3.png">

**launch.json:**
```
{
	// Use IntelliSense to learn about possible SWF debug attributes.
	// Hover to view descriptions of existing attributes.
	// For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
	"version": "0.2.0",
	"configurations": [
		{
			"type": "swf",
			"request": "launch",
			"name": "Launch SWF"//,
            //"preLaunchTask": "ActionScript: compile debug - asconfig.json"
		}
	]
}
```

**settings.json**
```
{
    "as3mxml.sdk.framework": "/Users/thisUser/Library/AIRSDK_MacOS"
}
```

**asconfig.json**
```
{
	"config": "air",
	"compilerOptions": {
		"source-path": [
			"src"
		],
		"output": "bin/Main.swf"
	},
	"mainClass": "Main",
	"application": "src/Main-app.xml"
}
```

**Main.mxml:**
```
<?xml version="1.0" encoding="utf-8"?>
<s:WindowedApplication xmlns:fx="http://ns.adobe.com/mxml/2009"
   xmlns:s="library://ns.adobe.com/flex/spark"
   xmlns:mx="library://ns.adobe.com/flex/mx">

	<s:layout>
		<s:BasicLayout/>
	</s:layout>

	<s:Label text="Hello World" horizontalCenter="0" verticalCenter="0"/>

</s:WindowedApplication>
```

**Main-app.xml:**
```
<?xml version="1.0" encoding="utf-8" ?>
<application xmlns="http://ns.adobe.com/air/application/33.1">
	<id>com.example.myAppName </id>
	<versionNumber>0.0.0</versionNumber>
	<filename>myAppName </filename>
	<name>myAppName </name>
	<initialWindow>
		<content>[Path to content will be replaced by Visual Studio Code]</content>
		<visible>true</visible>
	</initialWindow>
</application>
```
<img width="722" alt="Screen Shot 2021-12-07 at 8 25 05 AM" src="https://user-images.githubusercontent.com/80773129/145037383-3b188ef3-e3ec-410b-98f7-5ae5dc091ad0.png">

**Comment by ULSashido** [comment]
Update, added `"additionalOptions": "-locale en_US",` to asconfig.json and it got rid of the second Error

**Comment by ULSashido** [comment]
Debugging the App (F5) will display me this error message (hopefully provides a clue)
<img width="262" alt="Screen Shot 2021-12-07 at 10 10 27 AM" src="https://user-images.githubusercontent.com/80773129/145054802-56986a08-edb8-4047-a356-5296fa072e3e.png">
:

**Comment by joshtynjala** [comment]
Because you are building an app that uses the Flex framework, you need to set `as3mxml.sdk.framework` to the path of a **Flex SDK**. It looks to me like you are currently using the AIR SDK & Compiler, which can compile pure ActionScript code only. This SDK does not have any of the Flex classes, and it doesn't support MXML.

There's a special version of the AIR SDK that you can merge with a Flex SDK, if you want to use the latest version of AIR from HARMAN. On HARMAN's download page, you want to download the **AIR SDK for Flex Developers - to be overlaid onto a Flex SDK**, and then merge it with a Flex SDK.

**Comment by ULSashido** [comment]
I understand now. Thanks for that tip!

For Overlaying an AIR SDK with Flex, I see everyone refers to this page: https://helpx.adobe.com/x-productkb/multi/how-overlay-air-sdk-flex-sdk.html

It refers to a AdobeAIRSDK.**dmg**, now a days the SDK is just a zipped Folder. 
`hdiutil attach AdobeAIRSDK.dmg`

**Comment by joshtynjala** [comment]
It would be better to copy from AIR SDK and paste over Flex SDK. The AIR SDK contains files that should replace files in the Flex SDK. However, it's worth mentioning copy/paste on macOS tends to replace entire directories with the same name, instead of merging them, like Windows does.

With that in mind, I would recommend following the instructions for doing it in the terminal. It's okay if it the file isn't a DMG anymore. Just extract the ZIP and then change the first path of this command from the instructions:

```sh
cp -rf /Volumes/AIR\ SDK/* /path-to-empty-FLEXSDK-directory
```

For instance, if you extracted the archive to an _AIRSDK_Flex_MacOS_ folder on your desktop, the command might change like this.

```sh
cp -rf /Users/username/Desktop/AIRSDK_Flex_MacOS/* /path-to-empty-FLEXSDK-directory
```

**Comment by ULSashido** [comment]
Did another method, which was to copy the SDK which I know was working on old Mac into the new Mac and referenced this SDK in the VSCode & `settings.json`

When I run the App, I get only this now:
<img width="262" alt="Screen Shot 2021-12-08 at 7 03 27 AM" src="https://user-images.githubusercontent.com/80773129/145205440-4108ed57-f0a5-420b-b9ff-ecbc5e5973d4.png">

**Comment by ULSashido** [comment]
Finally got it to work! Needed a small replacement Main-app.xml to reflect the SDK version!

**Comment by joshtynjala** [comment]
I know you figured it out, but I wanted to add a couple of tips for your previous attempts that didn't work, so that this information might eventually show up on Google for people having similar issues.

> Compiler not found in SDK.

Based on your screenshot, it looks to me like you copied the AIR SDK into a completely empty directory. You need to copy it into a directory that contains a Flex SDK. It's unfortunate that Adobe named it _empty-FLEXSDK-directory_ in their instructions because it's not actually supposed to be empty.

> "Adobe AIR.framework" is damaged and can't be opened.

According to [this post](https://forum.starling-framework.org/d/23329-adobe-airframework-is-damaged) you can run this command in the terminal to fix this issue.

```
sudo xattr -r -d com.apple.quarantine AIRSDK_Folder
```

(this is probably explained in HARMAN's release notes too, but that was the easiest result to find on Google)
