### ISSUE TITLE
trying to get linux SDK to populate APACHE ROYALE

### ISSUE THREAD

**Issue by robo-loki** [BowlerHatLLC/vscode-as3mxml#609]
Hi guys-

I am trying to get SDK to show up ctrl shfit P.
I set in my .bashrc
PATH=$PATH:/home/megatron/php-7.4.29/bin:/usr/share/maven/bin:/home/megatron/apache-royale/royale-asjs/js/bin/:/usr/lib/jvm/jre-17-openjdk/bin:/home/megatron/.m2/repository/org/apache/royale/framework
export PATH
ROYAL_HOME=/home/megatron/.m2/repository/org/apache/royale/framework
export ROYAL_HOME
I run $ source .bashrc. Exit visual studio code. Come back in and the status bar indicates no sdk.
I had run ./mvnw install for all 3 : compiler asjs typedefs. It said it was putting them in the reactor .m2.
I gave it the path to the .swc which is /home/megatron/.m2/repository/org/apache/royale/framework.
I don't really oonsider this a bug. I just don't know what else to do to get it to detect and recognize sdk for apache royale.
I cant use moonshine or feather because it is windows and mac only.
thanks for any assistance - jim

**Comment by robo-loki** [comment]
Josh - I am actually not sure if I am ginving the right paths for the sdk. I just have apache royale for linux . I went into the soruces off my home directory and did ./mvwn install to each directory. I think that installed an SDK. not sure. They all said build success.
I can't use feathers because it is for windows and MAC but I am happy just to use apache royale. My code editor isn't detecting when I type something like var bd:BinaryData = new BinaryData(); and then like bd.readUTF(). It doesn't auto complete for any thing beginning with the letter R or W. I need the read and write metods for org.apache.royale.net .* THANKS!

**Comment by joshtynjala** [comment]
> ROYAL_HOME

You have a typo here. It should be `ROYALE_HOME` with an E.

You can also set `as3mxml.sdk.framework` in Visual Studio Code's settings. No need for environment variables.

> I went into the soruces off my home directory and did ./mvwn install to each directory. I think that installed an SDK. not sure

This will build the various artifacts for Maven, but it won't create a proper "distribution" of the SDK that you can use in an IDE. For that, you need to use the with-distribution profile.

More details about building from source with Maven:

https://github.com/apache/royale-asjs/wiki/Build-Apache-Royale-with-Maven

However, I recommend downloading a binary distribution instead of building from source. It's much easier. You only need to extract it into a directory.

You can get the latest binary distribution from here:

https://dlcdn.apache.org/royale/0.9.9/binaries/

I recommend apache-royale-0.9.9-bin-js.tar.gz for Linux. This is JS-only, with no support for SWF.

**Comment by robo-loki** [comment]
That is awesome Josh!

I read your request at the mailing list about getting binary with npm at
Apache Royale as I was looking into that too.
I reaffirmed that was the right course by taking a peak at moonshine.
I guess there is a 2FA thing going on with the upload of the binary for npm.
Thanks for the cool link about the binary.
I tried cygwin to build my extension that I want to use php_amf3.
There is a bug in cygwin. I followed an awesome guide on how to do
extensions with php in cygwin
and the bug persists even after following the guide. I don't want to
complain, so I will try to go with linux.
I am going to do a webcomplete capture of the cygwin guide with microsoft
edge.
I like JS only. Very cool.
https://developpaper.com/full-version-install-cygwin-on-windows-system-to-build-the-swote-test-environment/


THANKS,
jim
