### ISSUE TITLE
Question: Should "A conflict exists with inherited definition X in class Y" be a warning?

### ISSUE THREAD

**Issue by Adolio** [BowlerHatLLC/vscode-as3mxml#685]
Hi Josh,

When hiding a base method by reducing its scope generates an error in the editor but doesn't fail the compilation. 

Should this be therefore considered as a warning?

![Screenshot_2023-05-03_09-44-21](https://user-images.githubusercontent.com/1126990/235864388-201a24a8-7e3b-4054-8493-b1bc5eb2674c.png)

**Comment by joshtynjala** [comment]
I wasn't aware that you could hide a method by reducing its scope. I'll need to compare the various AS3 compilers to see if that's standard, or just a quirk of one of them.

**Comment by joshtynjala** [comment]
But all errors in vscode-as3mxml come from the Royale compiler (which was a fork of the Adobe AIR compiler, sometimes called ASC 2.0, donated to Apache). If it needs to change, it needs to change there.

**Comment by joshtynjala** [comment]
Finally got around to trying out various compilers.

- Royale reports the error mentioned in this issue description.

- ASC 2.0 (AIR SDK) compiles the code without any errors or warnings.

- Flex reports the following errors:

   ```
   ClassA.as(24): col: 19 Error: Incompatible override.

           private function methodA():void {}
                            ^

   ClassA.as(24): col: 19 Error: Overriding a function that is not marked for override.

           private function methodA():void {}
                            ^
   ```

**Comment by joshtynjala** [comment]
I tried placing `ClassA` and `ClassC` into separate files, so that I could instantiate both and call `methodA()` on both to see what the runtime behavior is when ASC 2.0 compiles successfully.

```as3
package com.example
{
	public class ClassA
	{
		public function ClassA()
		{
		}

		public function methodA():void
		{
			trace("ClassA.methodA");
		}
	}
}
```

```as3
package com.example
{
	public class ClassC extends ClassA
	{
		public function ClassC()
		{
		}

		private function methodA():void
		{
			trace("ClassC.methodA");
		}
	}
}
```

```as3
var a:ClassA = new ClassA();
a.methodA();

var c:ClassC = new ClassC();
c.methodA();
```

The debug output is:

```
ClassA.methodA
ClassA.methodA
```

Since thus code compiles successfully too, it means that ASC 2.0 is not reducing the scope of `methodA` from public to private. The original public `methodA` from `ClassA` is called for `ClassC`.

It is, in fact, possible to call the private version of `methodA()`, but it must happen inside `ClassC`.

```as3
package com.example
{
	public class ClassC extends ClassA
	{
		public function ClassC()
		{
			methodA();
		}

		private function methodA():void
		{
			trace("ClassC.methodA");
		}
	}
}
```

Keeping all of the other code the same, including calling the public version of `methodA` on both classes, the debug output becomes:

```
ClassA.methodA
ClassC.methodA
ClassA.methodA
```

You can call the public `methodA` inside `ClassC` too. You just need to use `public::methodA()`, with the `public::` namespace modifier.

So, in ASC 2.0, the private `methodA` and the public `methodA` are actually considered separate methods, even though they share the same name. Which one gets called depends on the context.

I wouldn't plan on the Royale compiler (which provides code intelligence for vscode-as3mxml) being updated to support this behavior, even optionally.

**Comment by Adolio** [comment]
Thanks a lot for having taken the time to dig into this compilation nightmare 😬 ...and sorry for having pushed you in there 😅 

It indeed makes no sense to "fixed" that in such context.
