### ISSUE TITLE
Adding -licenseDevID or -licenseFile to ADT commands

### ISSUE THREAD

**Issue by waveofthought-code** [BowlerHatLLC/vscode-as3mxml#761]
I'm aware of the the `additionalOptions` property in asconfig, but when I try adding these flags it errors out.  eg:
```
Error: unknown configuration variable 'licenseDevID <devID>'.
```
Is there a way to add additional options to _adt_ via asconfig, or at the very least supply these two specifically with special asconfig properties?

--------------
edited to add the bottom line of the output from `adt -help`:
```
All commands can be preceeded by '-licenseFile (path)adt.lic' or '-licenseDevID DevID' to override the use of the lib/adt.lic file
```

**Comment by joshtynjala** [comment]
`additionalOptions` is for the **mxmlc** compiler only. It does not affect options passed to **adt**.

Unfortunately, **adt** options are required to appear in a very specific order, unlike with **mxmlc**. So I've never added a field that would be the **adt** equivalent of `additionalOptions` because sometimes options need to be added to the beginning, sometimes at the end, or sometimes directly before or after a particular option somewhere in the middle.

When I get a chance, I'll add both `licenseFile` and `licenseDevID` to `airOptions`. I'm actually surprised that no one has brought this up before! I guess most people are placing their .lic file where it will be detected by **adt** automatically, so they haven't needed to specify either of these options. (I believe that location is _~/.airsdk/adt.lic_, or in the _lib_ directory of the AIR SDK).

**Comment by waveofthought-code** [comment]
Thanks Josh!  I just learned of the existence of these properties today, but it looks like they've been around for awhile.   They'll be useful to have included in asconfig, no doubt!
